// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEh40oyq-QXUqoTJoyDSdR49Jvg7XE0ZQ',
    appId: '1:1017740229638:web:1ecc48240574c412e95787',
    messagingSenderId: '1017740229638',
    projectId: 'affinity-79d0d',
    authDomain: 'affinity-79d0d.firebaseapp.com',
    storageBucket: 'affinity-79d0d.appspot.com',
    measurementId: 'G-N7DSNZW2SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLIYlGeiB9rENhkQCLpYTZnKA6_v5RZxw',
    appId: '1:1017740229638:android:4138a166ae43b13fe95787',
    messagingSenderId: '1017740229638',
    projectId: 'affinity-79d0d',
    storageBucket: 'affinity-79d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQUbJVc-u4BYAzbnE68tDTuo8uUgcFZ3g',
    appId: '1:1017740229638:ios:4683ad0f84dd217ce95787',
    messagingSenderId: '1017740229638',
    projectId: 'affinity-79d0d',
    storageBucket: 'affinity-79d0d.appspot.com',
    iosBundleId: 'com.example.affinity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQUbJVc-u4BYAzbnE68tDTuo8uUgcFZ3g',
    appId: '1:1017740229638:ios:9fd1862d025acf7fe95787',
    messagingSenderId: '1017740229638',
    projectId: 'affinity-79d0d',
    storageBucket: 'affinity-79d0d.appspot.com',
    iosBundleId: 'com.example.affinity.RunnerTests',
  );
}
